- name: Deactivate nginx start site
  file:
    dest: /etc/nginx/sites-enabled/start
    state: absent
  notify: 'reload nginx'

- name: Deactivate nginx wildfly site
  file:
    dest: /etc/nginx/sites-enabled/wildfly
    state: absent
  notify: 'reload nginx'

- name: Activate nginx maintenance site
  file:
    src: /etc/nginx/sites-available/maintenance
    dest: /etc/nginx/sites-enabled/maintenance
    state: link
  notify: 'reload nginx'
