- name: Deactivate nginx maintenance site
  file:
    name: /etc/nginx/sites-enabled/maintenance
    state: absent

- name: Activate nginx wildfly site
  file:
    src: /etc/nginx/sites-available/wildfly
    dest: /etc/nginx/sites-enabled/wildfly
    state: link

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
